#（此处请注意，arm架构请注意修改镜像名称以免拉错无法启动）
version: '3'
services:
  
  # 以下 phpmyadmin 主要是为了更为直观的供owner翻阅数据，不影响bot运行，如有其他合适软件，可注释内容 # xxxx
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - 8080:80  #映射端口可以自己改的
#    environment:
#      MYSQL_ROOT_PASSWORD: "123456"
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#    depends_on:
#      - mysql

  embyboss:
    image: jingwei520/sakura_embyboss:latest # ARM与AMD镜像名称相同，会自动加载适合的镜像
    container_name: embyboss
    restart: always
    network_mode: host
    volumes:
      - ./config.json:/app/config.json
      - ./log:/app/log
#    ports:
#      - '8838:8838' # 为api服务映射端口 host模式无需操作
